In [4]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 
import numpy as np

Instructions for updating:
non-resource variables are not supported in the long term


In [5]:
g = tf.Graph()

In [6]:
with g.as_default():
    x = tf.placeholder(dtype=tf.float32,
                      shape=(None, 2, 3),
                      name='input_x')
    x2 = tf.reshape(x, shape=(-1, 6),
                   name='x2')
    
    ## calculate the sum of each column
    xsum = tf.reduce_sum(x2, axis=0, name='col_sum')
    
    ## calculate the mean of each column
    xmean = tf.reduce_mean(x2, axis=0, name='col_mean')

In [8]:
with tf.Session(graph=g) as sess:
    x_array = np.arange(18).reshape(3,2,3)
    
    print('input shape: ', x_array.shape)
    print('Reshaped:\n', 
          sess.run(x2, feed_dict={x:x_array}))
    print('Column Sums:\n',
         sess.run(xsum, feed_dict={x:x_array}))
    print('Column Means:\n',
         sess.run(xmean, feed_dict={x:x_array}))

input shape:  (3, 2, 3)
Reshaped:
 [[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]]
Column Sums:
 [18. 21. 24. 27. 30. 33.]
Column Means:
 [ 6.  7.  8.  9. 10. 11.]
